/*
    FUNÇOES - ARGUMENTOS E PARAMETROS

    PARAMETROS É COMO SE ESTIVESSEMOS CRIANDO DENTRO DE UMA FUNCÃO VARIAVEIS
    ARGUMENTOS É COMO SE FOSSE OS VALORES DESSAS VARIAVEIS
    LEMBRANDO - OS PARAMETROS SÓ EXISTEM DENTRO DAS FUNÇÕES
    ESTUDAR - ESCOPO.

*/

function sum(n1,n2){
    console.log(`A soma entre ${n1} + ${n2} é: ` + (n1+n2))
} 

sum(5,6)